### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Pelirrojo** [devonmurphy/GathererImageGatherer#1]
Hi,

I'm working on a fork of your work and I would like to add some OSS license.
Any preference?

Thanks in advance,
Manuel

**Comment by devonmurphy** [comment]
Hello,

Thank you for the interest in the project, I just added a MIT license to the project, so feel free to do whatever you would like with the code. As you can see from the git history it has been a while since I have touched it, though it is pretty close to being functional.

Last time I was experimenting with it I remember calculating the hamming distance between perceptual hashes of a real card image to the gatherer card image and would often get values of 8-12 which is actually pretty good. The issue is that when the entire database was queried, there would be 1-10 other cards with equal or slightly less hamming distances, so it was hard to distinguish which was the right card. I was thinking of using video rather than a picture so that multiple frames could be analyzed. Since little effects like glare can really mess up your perceptual hash, taking multiple pictures from different angles could help offset environmental effects.

This how I tested this project last time:
- I downloaded all gatherer images using scrapedImages.py
- I built the database using buildBinaryDatabase.py
- I took a picture of a magic card with my phone
- I input the image to rotateCrop.py which rotates and crops the image and outputs a new image that it is only the card art
- I then input the cropped image from rotateCrop.py into getHash.py which has a bunch of functions to get perceptual hashes to get the perceptual hash
- Using the perceptual hash I then queried the postgres database for all cards with hamming distances less than 12 and got a list of 1-10 cards
